"""Migrate tables

Revision ID: 0ca586387911
Revises: 
Create Date: 2024-01-20 18:27:29.218708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ca586387911'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('opened_date', sa.Date(), nullable=True),
    sa.Column('closed_date', sa.Date(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('employee_number', sa.String(), nullable=True),
    sa.Column('employee_code', sa.String(), nullable=True),
    sa.Column('employee_name', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('main_phone', sa.String(), nullable=True),
    sa.Column('tin', sa.String(), nullable=True),
    sa.Column('iapa', sa.String(), nullable=True),
    sa.Column('npin', sa.String(), nullable=True),
    sa.Column('hiring_date', sa.Date(), nullable=True),
    sa.Column('dismissal_date', sa.Date(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('rank_id', sa.Integer(), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('employee_kind_code', sa.String(), nullable=True),
    sa.Column('employee_kind_name', sa.String(), nullable=True),
    sa.Column('employee_state', sa.String(), nullable=True),
    sa.Column('fte_id', sa.Integer(), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_table('timesheets',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('day_kind', sa.String(), nullable=True),
    sa.Column('plan_time', sa.Integer(), nullable=True),
    sa.Column('done_marks', sa.Integer(), nullable=True),
    sa.Column('planned_marks', sa.Integer(), nullable=True),
    sa.Column('begin_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('break_begin_time', sa.DateTime(), nullable=True),
    sa.Column('break_end_time', sa.DateTime(), nullable=True),
    sa.Column('input_time', sa.DateTime(), nullable=False),
    sa.Column('output_time', sa.DateTime(), nullable=False),
    sa.Column('facts', postgresql.ARRAY(sa.JSON()), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timesheets_employee_id'), 'timesheets', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timesheets_employee_id'), table_name='timesheets')
    op.drop_table('timesheets')
    op.drop_table('employees')
    op.drop_table('divisions')
    # ### end Alembic commands ###
